name: "build"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: testing action
      id: hello
      uses: ishitachawla/Check-Requirements@master
      with:
        repo_name: ${{ github.event.repository.name }}
        repo_owner: ${{github.repository_owner}}
        repo_branch: ${{github.ref}}
        GITHUB_TOKEN: ${{ secrets.PAT_Token }}
    - name: Get the output 
      run: echo ${{secrets.PAT_Token}}
