name: "repo-validation"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validating action repos
      id: checks_validation
      uses: ishitachawla/action-repo-validation@releases/3
      continue-on-error: true
      with:
        GITHUB_TOKEN: ${{ secrets.PAT_Token }}
        repositories: 'Requirement-testing,Check-Requirements'
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "index.json"
        json: "${{steps.checks_validation.outputs.validationResult}}"
    - name: validation result and  Commit file
      id: commit
      continue-on-error: true
      run: |
           cat index.json
           git config --local user.email "ishitachawla@github.com"
           git config --local user.name "ishitachawla"
           git pull
           git add --all
           if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
           else
             git commit -m "Add changes" -a
             echo "::set-output name=push::true"
           fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
